### ISSUE TITLE
Exception during BigQuery query

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/datalab#813] opened 2016-05-03 14:21 UTC
This morning the DataLab access to BigQuery (with green status) is not very reliable. Several times exception with similar query.
The script is querying more than 100 tables, after more than 3 executions with exception, each time on a different table.

```
<ipython-input-4-293efbb3b761> in table_size(table_name)
     93 
     94     return bq.Query('SELECT COUNT(DATE_TIME) AS ROWS FROM [{}]'
---> 95                     .format(table_name)).results()[0]["ROWS"]
     96 
     97 

/usr/local/lib/python2.7/dist-packages/gcp/bigquery/_query.pyc in results(self, use_cache)
    213     """
    214     if not use_cache or (self._results is None):
--> 215       self.execute(use_cache=use_cache)
    216     return self._results.results
    217 

/usr/local/lib/python2.7/dist-packages/gcp/bigquery/_query.pyc in execute(self, table_name, table_mode, use_cache, priority, allow_large_results)
    427     job = self.execute_async(table_name=table_name, table_mode=table_mode, use_cache=use_cache,
    428                              priority=priority, allow_large_results=allow_large_results)
--> 429     self._results = job.wait()
    430     return self._results
    431 

/usr/local/lib/python2.7/dist-packages/gcp/bigquery/_query_job.pyc in wait(self, timeout)
     78                                                     timeout=poll * 1000)
     79       except Exception as e:
---> 80         raise e
     81       if query_result['jobComplete']:
     82         if 'totalBytesProcessed' in query_result:

RequestException: Error encountered during execution. Retrying may solve the problem.
```

**Comment by gramster** [comment] 2016-05-03 23:02
That's a BQ error; it's not caused by Datalab. Perhaps try filing at https://code.google.com/p/google-bigquery/

**Comment by gramster** [comment] 2016-05-03 23:02
Closing as not a Datalab issue.

**Closed by gramster** 2016-05-03 23:02 UTC
