### ISSUE TITLE
Datalab chart map is not displayed correctly

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/datalab#733] opened 2015-12-26 09:14 UTC
Please find an example from the default installed notebook: ```notebooks/datalab/tutorials/Data/Interactive Charts with Google Charting APIs.ipynb```

The map is single color and the button's icons are not readable:
<img width="1023" alt="datalab map" src="https://cloud.githubusercontent.com/assets/8209940/12005769/592cb8be-ab6b-11e5-987b-c71ad8b3f4a0.png">
The screenshot is on my Chrome browser, on the Safari the single color is replaced by the map but the button icons are still unreadable.

**Comment by gramster** [comment] 2015-12-29 23:33
The buttons being unreadable is something we are aware of. The single color map means the map didn't load - the push pins can still be drawn independently. These are both Google Charts issues, not specific to Datalab.

**Comment by gramster** [comment] 2016-01-09 00:54
fixed in 16fb344839582fa15fb2ea891b5b3026e87c01f4

**Closed by gramster** 2016-01-09 00:54 UTC

**Comment by VelizarVESSELINOV** [comment] 2016-05-04 15:24
On my DataLab project is still not working map, what it is needed to deploy your fix on existing DataLab project?

**Comment by VelizarVESSELINOV** [comment] 2016-05-14 23:38
Works now :)

**Comment by Cecitux** [comment] 2016-07-19 01:01
@VelizarVESSELINOV  
@gramster 
Could you explain me how to result this issue, I have the following error for see a map.

![image](https://cloud.githubusercontent.com/assets/16903090/16935127/5672b228-4d22-11e6-948c-a019c737f011.png)


Thanks

**Comment by scottma** [comment] 2016-11-09 16:44
I have the same error here, wonder if anyone has found a solution to this.

**Comment by VelizarVESSELINOV** [comment] 2016-11-09 16:48
At the end, I stopped using `%%chart map` because of stability and limitation issues, JavaScript Google map call is more reliable, scalable, portable.

**Comment by qimingj** [comment] 2016-11-09 19:31
Can anyone share a bigquery table with me(qimingj@google.com) and the query to reproduce the issue? I cannot reproduce the error using our sample notebooks.

**Comment by magyarb** [comment] 2017-03-27 13:03
I can not use the %%chart map, because i get the API error: MissingKeyMapError. Where can i specify my API key?

**Comment by chmeyers** [comment] 2017-03-27 17:33
MissingKeyMapError is this issue: https://github.com/googledatalab/notebooks/issues/74

**Comment by yebrahim** [comment] 2017-03-27 17:39
Updated that issue with one possible work around to embed your key in the notebook.
